In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [6]:
a = [[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [10]:
A = np.array(a)
A

2

In [14]:
ndim = A.ndim
ndim


2

In [15]:
shape = A.shape
shape


(3, 3)

In [16]:
size = A.size
size

In [18]:
A[1,2]

23

In [19]:
A[1][2]



23

In [24]:
A[0][0:2]


array([11, 12])

In [29]:
A[0:2, 2]

array([13, 23])

In [4]:
import numpy as np

X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])

Z = X + Y

array([[3, 1],
       [1, 3]])

In [5]:
Y = np.array([[2, 1], [1, 2]])
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [7]:
Y = np.array([[2, 1], [1, 2]])
X = np.array([[1, 0], [0, 1]])

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [9]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

Z = A.dot(B)
Z

array([[0, 2],
       [0, 2]])

In [10]:
C = np.array([[1,1],[2,2],[3,3]])
C.T

array([[1, 2, 3],
       [1, 2, 3]])